production:
  clients:
    default:
      database: sombra_production
      hosts:
        - <%= ENV["SOMBRA_MONGODB_HOST"] %>
      options:
        user: <%= ENV["SOMBRA_MONGODB_USER"] %>
        password: <%= ENV["SOMBRA_MONGODB_PASSWORD"] %>
        roles:
          - <%= ENV["SOMBRA_MONGODB_ROLES"] %>
        auth_mech: :scram
        auth_source: <%= ENV["SOMBRA_MONGODB_AUTH_SOURCE"] %>
        max_pool_size: <%= ENV["SOMBRA_MONGODB_MAX_POOL_SIZE"].to_i %>
        min_pool_size: <%= ENV["SOMBRA_MONGODB_MIN_POOL_SIZE"].to_i %>
        wait_queue_timeout: 5
        connect_timeout: 2
        socket_timeout: 2
        use_utc: true

development:
  clients:
    default:
      database: sombra_development
      hosts:
        - <%= ENV["SOMBRA_MONGODB_HOST"] %>
      options:
        user: <%= ENV["SOMBRA_MONGODB_USER"] %>
        password: <%= ENV["SOMBRA_MONGODB_PASSWORD"] %>
        roles:
          - <%= ENV["SOMBRA_MONGODB_ROLES"] %>
        auth_mech: :scram
        auth_source: <%= ENV["SOMBRA_MONGODB_AUTH_SOURCE"] %>
        max_pool_size: <%= ENV["SOMBRA_MONGODB_MAX_POOL_SIZE"].to_i %>
        min_pool_size: <%= ENV["SOMBRA_MONGODB_MIN_POOL_SIZE"].to_i %>
        wait_queue_timeout: 5
        connect_timeout: 2
        socket_timeout: 2
        use_utc: true

test:
  clients:
    default:
      database: sombra_test
      hosts:
        - <%= ENV["SOMBRA_MONGODB_HOST"] %>
      options:
        user: <%= ENV["SOMBRA_MONGODB_USER"] %>
        password: <%= ENV["SOMBRA_MONGODB_PASSWORD"] %>
        roles:
          - <%= ENV["SOMBRA_MONGODB_ROLES"] %>
        auth_mech: :scram
        auth_source: <%= ENV["SOMBRA_MONGODB_AUTH_SOURCE"] %>
        max_pool_size: <%= ENV["SOMBRA_MONGODB_MAX_POOL_SIZE"].to_i %>
        min_pool_size: <%= ENV["SOMBRA_MONGODB_MIN_POOL_SIZE"].to_i %>
        wait_queue_timeout: 5
        connect_timeout: 2
        socket_timeout: 2
        use_utc: true
