development:
  secret_key_base: a455553900ff0f1cff4aea3c846db75f9780dbb8e1d6c305e051d03f5269d976d8c0a12832186362fd394bf0cf0afec1ebc8ea8bb108543daa9254bd4928dfb3
  token_es256_priv: "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEILC8878HkilwY6i1ZRqk2sQM4999Bo/y3ZHwiOKvsDdnoAoGCCqGSM49\nAwEHoUQDQgAElAfxdt6MZxXc4TsZROhm8QPnoDm5ILVK9el6kU9xd+3Pnb3yOBsL\nTnuX9/x2c8HIQIoxEs8IlreBQndy3CvRJQ==\n-----END EC PRIVATE KEY-----\n"
  token_es256_pub: "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAElAfxdt6MZxXc4TsZROhm8QPnoDm5\nILVK9el6kU9xd+3Pnb3yOBsLTnuX9/x2c8HIQIoxEs8IlreBQndy3CvRJQ==\n-----END PUBLIC KEY-----\n"

test:
  secret_key_base: a07db8c90bd628ec8ba7841dd056749f25f796d19e0bb393343b64f7acfb5199e3e675891337417dbc6bdb4133d5be6efee2df560791e7fdfb11feacd375708a
  token_es256_priv: "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEILC8878HkilwY6i1ZRqk2sQM4999Bo/y3ZHwiOKvsDdnoAoGCCqGSM49\nAwEHoUQDQgAElAfxdt6MZxXc4TsZROhm8QPnoDm5ILVK9el6kU9xd+3Pnb3yOBsL\nTnuX9/x2c8HIQIoxEs8IlreBQndy3CvRJQ==\n-----END EC PRIVATE KEY-----\n"
  token_es256_pub: "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAElAfxdt6MZxXc4TsZROhm8QPnoDm5\nILVK9el6kU9xd+3Pnb3yOBsLTnuX9/x2c8HIQIoxEs8IlreBQndy3CvRJQ==\n-----END PUBLIC KEY-----\n"


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  token_es256_priv: <%= ENV["CAFMAL_API_TOKEN_SECRET_PRIVATE"] %>
  token_es256_pub: <%= ENV["CAFMAL_API_TOKEN_SECRET_PUBLIC"] %>
